# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-21 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicProfessionalQualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('date', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('department', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EducationInstitutions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=300)),
                ('from_date', models.CharField(max_length=30)),
                ('to_date', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('surname', models.CharField(max_length=100)),
                ('othername', models.CharField(max_length=100)),
                ('maidenname', models.CharField(blank=True, max_length=100)),
                ('spouse_name', models.CharField(blank=True, max_length=30)),
                ('gender', models.CharField(max_length=20)),
                ('date_of_birth', models.CharField(max_length=20)),
                ('homeplace', models.TextField()),
                ('lga', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('phone_1', models.CharField(blank=True, max_length=30)),
                ('phone_2', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(max_length=20)),
                ('designation', models.CharField(max_length=20)),
                ('gl', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=40)),
                ('date_of_first_Appt', models.CharField(max_length=20)),
                ('date_of_conf', models.CharField(max_length=20)),
                ('name_employer', models.CharField(blank=True, max_length=20)),
                ('date_of_transfer', models.CharField(blank=True, max_length=20)),
                ('pre_rank', models.CharField(blank=True, max_length=20)),
                ('pre_gl', models.CharField(blank=True, max_length=20)),
                ('pre_salary', models.CharField(blank=True, max_length=20)),
                ('date_of_last_promotion', models.CharField(blank=True, max_length=20)),
                ('staff_no', models.CharField(blank=True, max_length=30)),
                ('account_num', models.CharField(blank=True, max_length=30)),
                ('occupant', models.BooleanField()),
                ('nok_name_1', models.CharField(blank=True, max_length=30)),
                ('nok_address_1', models.CharField(blank=True, max_length=45)),
                ('nok_name_2', models.CharField(blank=True, max_length=30)),
                ('nok_address_2', models.CharField(blank=True, max_length=45)),
            ],
        ),
    ]
