# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-01 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nok_relationship_1',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AddField(
            model_name='profile',
            name='nok_relationship_2',
            field=models.CharField(blank=True, max_length=45),
        ),
    ]
