# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-14 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20181101_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pre_gl',
            field=models.IntegerField(),
        ),
    ]
