# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-29 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20181114_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='abbr',
            field=models.CharField(default='opps', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pre_gl',
            field=models.CharField(max_length=20),
        ),
    ]
