# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-21 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('field_type', models.CharField(max_length=30)),
                ('table_id', models.CharField(max_length=100)),
                ('emp_field', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Nysc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Siwes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TableData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col_id', models.CharField(max_length=100)),
                ('row_id', models.CharField(default='1', max_length=100)),
                ('table_id', models.CharField(default='1', max_length=100)),
                ('data', models.CharField(max_length=100)),
                ('month', models.CharField(default='no date', max_length=25)),
                ('quater', models.CharField(default='no date', max_length=25)),
                ('year', models.CharField(default='no date', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='TableTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Todos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_id', models.CharField(max_length=100)),
                ('employee_id', models.CharField(max_length=100)),
                ('effective_date', models.CharField(max_length=100)),
                ('field_id', models.CharField(max_length=100)),
            ],
        ),
    ]
