# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-21 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Row_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(default='no date', max_length=25)),
                ('quater', models.CharField(default='no date', max_length=25)),
                ('year', models.CharField(default='no date', max_length=25)),
            ],
        ),
        migrations.RenameField(
            model_name='tabledata',
            old_name='month',
            new_name='month_d',
        ),
        migrations.RenameField(
            model_name='tabledata',
            old_name='quater',
            new_name='quater_d',
        ),
        migrations.RenameField(
            model_name='tabledata',
            old_name='year',
            new_name='year_d',
        ),
    ]
